Contact.create!([
  {first_name: "Alejandra", last_name: "Schmitt", email: "alejandra_schmitt@yahoo.com", phone_number: "(534) 499-0121", middle_name: nil, bio: nil},
  {first_name: "Gerda", last_name: "Emard", email: "emard.gerda@hotmail.com", phone_number: "1-914-600-1884", middle_name: nil, bio: nil},
  {first_name: "Camille", last_name: "Jakubowski", email: "camille.jakubowski@gmail.com", phone_number: "258.230.5305 x4706", middle_name: nil, bio: nil},
  {first_name: "Kellen", last_name: "Mohr", email: "mohr_kellen@yahoo.com", phone_number: "801.031.5130", middle_name: nil, bio: nil},
  {first_name: "Janae", last_name: "Collins", email: "collins.janae@yahoo.com", phone_number: "1-658-476-1479", middle_name: nil, bio: nil},
  {first_name: "Alden", last_name: "Zieme", email: "zieme.alden@hotmail.com", phone_number: "1-772-332-8331 x3359", middle_name: nil, bio: nil},
  {first_name: "Rico", last_name: "Gleason", email: "rico.gleason@gmail.com", phone_number: "592.757.5728", middle_name: nil, bio: nil},
  {first_name: "Nedra", last_name: "Lynch", email: "nedra_lynch@gmail.com", phone_number: "688.959.8836 x0745", middle_name: nil, bio: nil},
  {first_name: "Pete", last_name: "Hayes", email: "pete_hayes@gmail.com", phone_number: "1-818-953-3182", middle_name: nil, bio: nil},
  {first_name: "Oswaldo", last_name: "Smith", email: "smith.oswaldo@hotmail.com", phone_number: "(508) 704-5207", middle_name: nil, bio: nil},
  {first_name: "Wilhelm", last_name: "Dicki", email: "wilhelm_dicki@gmail.com", phone_number: "194-221-3875 x4443", middle_name: nil, bio: nil},
  {first_name: "Jan", last_name: "Rodriguez", email: "rodriguez.jan@hotmail.com", phone_number: "664.128.9666", middle_name: nil, bio: nil},
  {first_name: "Dillan", last_name: "Mante", email: "dillan.mante@gmail.com", phone_number: "(367) 547-3632 x89500", middle_name: nil, bio: nil},
  {first_name: "Alfreda", last_name: "Fisher", email: "fisher_alfreda@hotmail.com", phone_number: "809.265.5671 x1621", middle_name: nil, bio: nil},
  {first_name: "Deborah", last_name: "Mraz", email: "deborah.mraz@yahoo.com", phone_number: "1-272-556-7730 x9859", middle_name: nil, bio: nil},
  {first_name: "Mattie", last_name: "Botsford", email: "botsford_mattie@hotmail.com", phone_number: "610-350-1338", middle_name: nil, bio: nil},
  {first_name: "Darius", last_name: "Franecki", email: "franecki.darius@gmail.com", phone_number: "(127) 336-2720 x38922", middle_name: nil, bio: nil},
  {first_name: "Mohammed", last_name: "Nolan", email: "mohammed.nolan@hotmail.com", phone_number: "103-024-1611 x9146", middle_name: nil, bio: nil},
  {first_name: "Coralie", last_name: "Mraz", email: "coralie_mraz@gmail.com", phone_number: "122-203-7063", middle_name: nil, bio: nil},
  {first_name: "Emory", last_name: "Abernathy", email: "emory_abernathy@gmail.com", phone_number: "1-737-953-8392 x054", middle_name: nil, bio: nil},
  {first_name: "Antwan", last_name: "Schroeder", email: "schroeder.antwan@gmail.com", phone_number: "1-361-415-6117", middle_name: nil, bio: nil},
  {first_name: "Macie", last_name: "Walker", email: "walker_macie@yahoo.com", phone_number: "509.577.2686 x3766", middle_name: nil, bio: nil},
  {first_name: "Clare", last_name: "Lemke", email: "lemke_clare@yahoo.com", phone_number: "1-149-565-3504 x2337", middle_name: nil, bio: nil},
  {first_name: "Gregoria", last_name: "Satterfield", email: "satterfield_gregoria@yahoo.com", phone_number: "(564) 834-9552", middle_name: nil, bio: nil},
  {first_name: "Ashton", last_name: "Feil", email: "ashton_feil@hotmail.com", phone_number: "579-489-7886", middle_name: nil, bio: nil},
  {first_name: "Wanda", last_name: "Wunsch", email: "wanda_wunsch@yahoo.com", phone_number: "1-310-044-5323 x549", middle_name: nil, bio: nil},
  {first_name: "Juliet", last_name: "Conroy", email: "conroy.juliet@gmail.com", phone_number: "(766) 311-5356", middle_name: nil, bio: nil},
  {first_name: "Paula", last_name: "Schultz", email: "paula.schultz@hotmail.com", phone_number: "(500) 739-8749 x305", middle_name: nil, bio: nil},
  {first_name: "Hosea", last_name: "Balistreri", email: "hosea_balistreri@hotmail.com", phone_number: "(227) 835-7295", middle_name: nil, bio: nil},
  {first_name: "Adriana", last_name: "Hermann", email: "hermann_adriana@hotmail.com", phone_number: "1-383-788-7152 x81075", middle_name: nil, bio: nil},
  {first_name: "Dave", last_name: "Fadel", email: "dave.fadel@yahoo.com", phone_number: "529.377.3212 x134", middle_name: nil, bio: nil},
  {first_name: "Waldo", last_name: "Christiansen", email: "waldo_christiansen@yahoo.com", phone_number: "346-760-0423", middle_name: nil, bio: nil},
  {first_name: "Ona", last_name: "Marks", email: "marks_ona@hotmail.com", phone_number: "(670) 270-1458 x3368", middle_name: nil, bio: nil},
  {first_name: "Nikko", last_name: "Fisher", email: "nikko.fisher@hotmail.com", phone_number: "(325) 821-9086", middle_name: nil, bio: nil},
  {first_name: "Sadie", last_name: "Marvin", email: "marvin.sadie@yahoo.com", phone_number: "920.060.6639", middle_name: nil, bio: nil},
  {first_name: "Terrill", last_name: "Wilderman", email: "wilderman.terrill@yahoo.com", phone_number: "456.156.8415", middle_name: nil, bio: nil},
  {first_name: "Shemar", last_name: "Wisozk", email: "wisozk.shemar@yahoo.com", phone_number: "(159) 899-0691 x61458", middle_name: nil, bio: nil},
  {first_name: "Robbie", last_name: "Adams", email: "adams_robbie@gmail.com", phone_number: "312.918.3108", middle_name: nil, bio: nil},
  {first_name: "Jefferey", last_name: "Ziemann", email: "jefferey_ziemann@gmail.com", phone_number: "(145) 232-8547", middle_name: nil, bio: nil},
  {first_name: "Newton", last_name: "Davis", email: "davis.newton@yahoo.com", phone_number: "851-495-2079", middle_name: nil, bio: nil},
  {first_name: "Elnora", last_name: "Bahringer", email: "elnora_bahringer@gmail.com", phone_number: "791.214.1782", middle_name: nil, bio: nil},
  {first_name: "Jensen", last_name: "Hyatt", email: "hyatt.jensen@yahoo.com", phone_number: "839-744-3217 x634", middle_name: nil, bio: nil},
  {first_name: "Sammie", last_name: "Skiles", email: "skiles.sammie@gmail.com", phone_number: "397-774-2151", middle_name: nil, bio: nil},
  {first_name: "America", last_name: "Schroeder", email: "america_schroeder@yahoo.com", phone_number: "448-765-5540", middle_name: nil, bio: nil},
  {first_name: "Micah", last_name: "Thiel", email: "thiel_micah@hotmail.com", phone_number: "803-697-3843", middle_name: nil, bio: nil},
  {first_name: "Milo", last_name: "Emard", email: "emard_milo@gmail.com", phone_number: "818-688-6574", middle_name: nil, bio: nil},
  {first_name: "Eugene", last_name: "Gerlach", email: "eugene.gerlach@gmail.com", phone_number: "(992) 138-9700", middle_name: nil, bio: nil},
  {first_name: "Jordon", last_name: "Turcotte", email: "turcotte_jordon@gmail.com", phone_number: "1-610-107-8153", middle_name: nil, bio: nil},
  {first_name: "Hollis", last_name: "Roob", email: "hollis_roob@gmail.com", phone_number: "216.637.7301 x822", middle_name: nil, bio: nil},
  {first_name: "Ayden", last_name: "Reinger", email: "ayden.reinger@gmail.com", phone_number: "330.759.8257 x777", middle_name: nil, bio: nil},
  {first_name: "Dannie", last_name: "Moore", email: "dannie.moore@hotmail.com", phone_number: "671.393.0850 x93615", middle_name: nil, bio: nil},
  {first_name: "Madelyn", last_name: "Emard", email: "madelyn_emard@hotmail.com", phone_number: "1-568-932-3847", middle_name: nil, bio: nil},
  {first_name: "Lennie", last_name: "Lindgren", email: "lennie_lindgren@hotmail.com", phone_number: "456.550.2514 x341", middle_name: nil, bio: nil},
  {first_name: "Concepcion", last_name: "Wiegand", email: "wiegand_concepcion@gmail.com", phone_number: "206.789.6806 x8564", middle_name: nil, bio: nil},
  {first_name: "Brendan", last_name: "DuBuque", email: "dubuque_brendan@gmail.com", phone_number: "1-412-678-5668 x73462", middle_name: nil, bio: nil},
  {first_name: "Duane", last_name: "DuBuque", email: "duane.dubuque@gmail.com", phone_number: "777-321-5658 x0948", middle_name: nil, bio: nil},
  {first_name: "Myrl", last_name: "Kovacek", email: "myrl.kovacek@hotmail.com", phone_number: "909.971.0541", middle_name: nil, bio: nil},
  {first_name: "Montana", last_name: "Ledner", email: "montana_ledner@hotmail.com", phone_number: "1-811-792-0185 x62176", middle_name: nil, bio: nil},
  {first_name: "Rosemarie", last_name: "Trantow", email: "rosemarie_trantow@hotmail.com", phone_number: "183-133-8385", middle_name: nil, bio: nil},
  {first_name: "Emerald", last_name: "Herzog", email: "herzog.emerald@gmail.com", phone_number: "734.926.6997 x3597", middle_name: nil, bio: nil},
  {first_name: "Audrey", last_name: "Borer", email: "borer_audrey@hotmail.com", phone_number: "1-392-303-0798 x701", middle_name: nil, bio: nil},
  {first_name: "Ally", last_name: "Jast", email: "ally_jast@yahoo.com", phone_number: "481.405.3974 x349", middle_name: nil, bio: nil},
  {first_name: "Lura", last_name: "Runolfsdottir", email: "lura_runolfsdottir@hotmail.com", phone_number: "(724) 078-1385 x56817", middle_name: nil, bio: nil},
  {first_name: "Maritza", last_name: "Fadel", email: "maritza_fadel@gmail.com", phone_number: "744-203-2601 x9632", middle_name: nil, bio: nil},
  {first_name: "Bianka", last_name: "Reilly", email: "bianka.reilly@gmail.com", phone_number: "836-191-2994", middle_name: nil, bio: nil},
  {first_name: "Vicenta", last_name: "Sipes", email: "sipes_vicenta@yahoo.com", phone_number: "271.377.2453", middle_name: nil, bio: nil},
  {first_name: "Carlee", last_name: "McLaughlin", email: "carlee.mclaughlin@yahoo.com", phone_number: "916-123-7703 x9450", middle_name: nil, bio: nil},
  {first_name: "Darren", last_name: "Rogahn", email: "darren.rogahn@hotmail.com", phone_number: "184.504.0459 x854", middle_name: nil, bio: nil},
  {first_name: "Mustafa", last_name: "Hegmann", email: "mustafa_hegmann@gmail.com", phone_number: "(645) 361-7934", middle_name: nil, bio: nil},
  {first_name: "Sienna", last_name: "Bogan", email: "sienna.bogan@gmail.com", phone_number: "(465) 377-5856", middle_name: nil, bio: nil},
  {first_name: "Clementine", last_name: "Jacobi", email: "jacobi_clementine@gmail.com", phone_number: "688.580.6748 x4139", middle_name: nil, bio: nil},
  {first_name: "Clement", last_name: "Walker", email: "clement.walker@hotmail.com", phone_number: "1-655-283-1052", middle_name: nil, bio: nil},
  {first_name: "Ottilie", last_name: "Rohan", email: "rohan_ottilie@gmail.com", phone_number: "811-781-2443 x413", middle_name: nil, bio: nil},
  {first_name: "Sammy", last_name: "Lindgren", email: "sammy_lindgren@yahoo.com", phone_number: "1-489-372-3136", middle_name: nil, bio: nil},
  {first_name: "Ferne", last_name: "Baumbach", email: "baumbach.ferne@gmail.com", phone_number: "1-968-487-6578 x113", middle_name: nil, bio: nil},
  {first_name: "Willie", last_name: "Marvin", email: "willie.marvin@gmail.com", phone_number: "941-244-5837", middle_name: nil, bio: nil},
  {first_name: "Rhoda", last_name: "McClure", email: "rhoda.mcclure@hotmail.com", phone_number: "759-215-9625", middle_name: nil, bio: nil},
  {first_name: "Litzy", last_name: "Rutherford", email: "litzy_rutherford@yahoo.com", phone_number: "1-204-410-0057 x0021", middle_name: nil, bio: nil},
  {first_name: "Kayden", last_name: "Harber", email: "harber.kayden@gmail.com", phone_number: "1-819-177-8333 x9028", middle_name: nil, bio: nil},
  {first_name: "Nicola", last_name: "Reilly", email: "reilly_nicola@gmail.com", phone_number: "480-071-3705 x539", middle_name: nil, bio: nil},
  {first_name: "Anika", last_name: "Quigley", email: "anika.quigley@yahoo.com", phone_number: "472.694.4163 x50040", middle_name: nil, bio: nil},
  {first_name: "Monty", last_name: "Gaylord", email: "gaylord_monty@yahoo.com", phone_number: "559-035-6935 x46975", middle_name: nil, bio: nil},
  {first_name: "Scot", last_name: "Ward", email: "ward.scot@gmail.com", phone_number: "707-612-6494 x28460", middle_name: nil, bio: nil},
  {first_name: "Brando", last_name: "Dibbert", email: "dibbert_brando@hotmail.com", phone_number: "(881) 401-8420", middle_name: nil, bio: nil},
  {first_name: "Rocio", last_name: "Adams", email: "adams_rocio@gmail.com", phone_number: "(336) 896-7288 x2553", middle_name: nil, bio: nil},
  {first_name: "Mose", last_name: "McClure", email: "mose_mcclure@gmail.com", phone_number: "428-222-0233", middle_name: nil, bio: nil},
  {first_name: "Aleen", last_name: "Aufderhar", email: "aufderhar_aleen@yahoo.com", phone_number: "138.269.7401", middle_name: nil, bio: nil},
  {first_name: "Ashtyn", last_name: "Kunze", email: "ashtyn_kunze@gmail.com", phone_number: "738.079.2043 x512", middle_name: nil, bio: nil},
  {first_name: "Santos", last_name: "Graham", email: "santos_graham@yahoo.com", phone_number: "(339) 244-7281 x373", middle_name: nil, bio: nil},
  {first_name: "Lillie", last_name: "Block", email: "block_lillie@yahoo.com", phone_number: "835.652.8639 x1936", middle_name: nil, bio: nil},
  {first_name: "Alda", last_name: "Langworth", email: "alda.langworth@hotmail.com", phone_number: "(505) 266-4959 x54655", middle_name: nil, bio: nil},
  {first_name: "Neil", last_name: "Ziemann", email: "neil.ziemann@gmail.com", phone_number: "308.445.0668 x2193", middle_name: nil, bio: nil},
  {first_name: "Christelle", last_name: "Schmeler", email: "schmeler.christelle@hotmail.com", phone_number: "(696) 059-7735", middle_name: nil, bio: nil},
  {first_name: "Cory", last_name: "Morissette", email: "cory_morissette@hotmail.com", phone_number: "(301) 615-4582 x2889", middle_name: nil, bio: nil},
  {first_name: "Hudson", last_name: "Dicki", email: "hudson_dicki@yahoo.com", phone_number: "392.471.0316 x271", middle_name: nil, bio: nil},
  {first_name: "Vladimir", last_name: "Huel", email: "huel.vladimir@gmail.com", phone_number: "(345) 294-4538 x19916", middle_name: nil, bio: nil},
  {first_name: "Audreanne", last_name: "Schmeler", email: "audreanne_schmeler@hotmail.com", phone_number: "(680) 233-6516 x5758", middle_name: nil, bio: nil},
  {first_name: "Michale", last_name: "Spencer", email: "spencer_michale@gmail.com", phone_number: "851-785-5541 x501", middle_name: nil, bio: nil},
  {first_name: "Izaiah", last_name: "Zboncak", email: "zboncak_izaiah@gmail.com", phone_number: "(949) 250-3244", middle_name: nil, bio: nil},
  {first_name: "joe", last_name: "john", email: "joe@john.com", phone_number: "345678", middle_name: nil, bio: nil},
  {first_name: "Linnea", last_name: "Green", email: "linnea.green@yahoo.com", phone_number: "310-631-7773", middle_name: "asdfksadkjf", bio: nil},
  {first_name: "gggg", last_name: "gggg", email: "ggg", phone_number: "gggg", middle_name: "gggg", bio: nil},
  {first_name: "aljksdhf", last_name: "ashdfkjash", email: "email", phone_number: "4567", middle_name: "asdhfj", bio: "alksdjf;lksadjf;asdjflksadjflasdfjlasdfjlasdjf;lsdafjklasdfj;lasdfj;laksdjf;laksdjfl;kasdjfl;asdkjfl;adskjfso;dfj;oiajflakewjf;aweijfoiwaejfweaifjaweifjwealkdsfjlk;jvoadvaofmcoiejn oeaofj         asakdfjlkdafngjlascnouweFNLKSCLMWEAUFASDK"}
])

# 100.times do
#   first_name = Faker::Name.first_name
#   last_name = Faker::Name.last_name

#   contact = Contact.new(
#     first_name: first_name,
#     last_name: last_name,
#     email: Faker::Internet.free_email("#{first_name}.#{last_name}"),
#     phone_number: Faker::PhoneNumber.phone_number
#   )
#   contact.save
# end
